service:
  golangci-lint-version: 1.12.5

linters:
  enable-all: true
  disable:
  - goconst
  - gocritic
  - gocyclo
  - gochecknoglobals
  - lll
  - scopelint
  fast: false

run:
  deadline: 1m

linters-settings:
  errcheck:
    ignore: "fmt:.*,gopkg.in/go-playground/validator.v9:.*RegisterValidation"
