version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/k-kinzal/aliases
    steps:
    - checkout
    - restore_cache:
        key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
        paths:
        - /go/src/github.com/k-kinzal/aliases/vendor
    - run: dep ensure -vendor-only=true
    - save_cache:
        key: gopkg-{{ .Branch }}-{{ checksum "Gopkg.lock" }}
        paths:
        - /go/src/github.com/k-kinzal/aliases/vendor
    - run: go build -ldflags "-s -w" -o ./dist/aliases .
    - persist_to_workspace:
        root: ./
        paths:
        - "*"

  test:
    docker:
    - image: circleci/golang:1.11.4
    working_directory: /go/src/github.com/k-kinzal/aliases
    steps:
    - attach_workspace:
        at: ./
    - run: go test ./... -v

  integration:
    machine: true
    steps:
    - attach_workspace:
        at: ./
    - run:
        name: Integration Test
        command: |
          find test/integration/*/test.sh | xargs -I{} /bin/sh -c "{} || exit 255 && echo pass {}"

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test:
        requires:
        - build
    - integration:
        requires:
        - build